
variables:
  SONAR_URL: http://192.168.100.205:9000
  GITLAB_URL: https://code.haylion.cn/im/maas_taxi_driver_android.git
  GITLAB_TOKEN: 9DepJ28wyRzG6mFBh9z3
  SONAR_TOKEN: c6794cd57dd4512aa1197e9af302200ba51e79c3

stages:
  - sonarqube
  - build
  - test
  - deploy


sonarqube:
  stage: sonarqube
  only:
    - master
  when:
    manual
  before_script:
    - source /etc/profile
    - chmod +x ./gradlew
  script:
    - ./gradlew sonarqube  -Dsonar.host.url=$SONAR_URL  -Dsonar.login=$SONAR_TOKEN
  tags:
    - dev



.build_template: &build
  stage: build
  before_script:
    - chmod +x ./gradlew
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 day
    paths:
      - app/build/outputs/
  retry: 1
  tags:
    - dev

build:dev:
  <<: *build
  script:
    - ./gradlew assembleDebug

build:test:
  <<: *build
  script:
    - ./gradlew assembleBeta

build:prod:
  <<: *build
  script:
    - ./gradlew assembleRelease



.test_template: &test
  stage: test
  only:
    - master
    - develop
  when: manual
  artifacts:
    when: on_failure
    expire_in: 3 days
    paths:
      - app/build/reports/tests/
  tags:
    - dev

unit:test:
  <<: *test
  script:
    - echo $CI_JOB_NAME
#    - ./gradlew test

instrumentation:test:
  <<: *test
  script:
    - echo $CI_JOB_NAME
#    - ./start-emulators.sh
#    - ./gradlew connectedAndroidTest
#    - ./stop-emulators.sh



.deploy_template: &deploy
  stage: deploy
  before_script:
    - chmod +x ./deploy.sh
    - chmod +x ./jq-linux32
  only:
    - master
    - develop
  when: manual
  tags:
    - dev

deploy:dev:
  <<: *deploy
  script:
    - ./deploy.sh $CI_JOB_NAME
  dependencies:
    - build:dev

deploy:test:
  <<: *deploy
  script:
    - ./deploy.sh $CI_JOB_NAME
  dependencies:
    - build:test

deploy:prod:
  <<: *deploy
  script:
    - ./deploy.sh $CI_JOB_NAME
  dependencies:
    - build:prod



